// Self-check for the rack layout subsystem. No test framework —
// `node checkLayout.js`. The pure sections always run; the DB sections are
// skipped with a notice when MySQL is unreachable.
import assert from 'node:assert/strict';
import {
  binsForGroup, buildTargetBins, coalesceRackGroups, diffLayout, findBlockers,
} from './src/services/layoutService.js';

const ok = (label) => console.log(`  ✓ ${label}`);

// Bin sets are compared as sets, not sequences — the order two different group
// lists emit them in is not what is being asserted.
const binOrder = (a, b) =>
  a.rack_no - b.rack_no || a.shelf_no - b.shelf_no || a.bin_no - b.bin_no;

// ── bins generated by one group ───────────────────────────────────────────
const one = binsForGroup({ rack_from: 1, rack_to: 2, shelves: 3, bins: 4, bin_capacity: 100 });
assert.equal(one.length, 2 * 3 * 4, 'racks × shelves × bins');
assert.deepEqual(one[0], { rack_no: 1, shelf_no: 1, bin_no: 1, capacity: 100 });
assert.deepEqual(one.at(-1), { rack_no: 2, shelf_no: 3, bin_no: 4, capacity: 100 });
ok('a group generates exactly racks × shelves × bins');

// A group starting partway up carries its own rack numbers — that is what makes
// appending work without renumbering anything already on the floor.
const appended = binsForGroup({ rack_from: 51, rack_to: 60, shelves: 2, bins: 2, bin_capacity: 40 });
assert.equal(appended.length, 10 * 2 * 2);
assert.equal(Math.min(...appended.map((b) => b.rack_no)), 51);
assert.equal(Math.max(...appended.map((b) => b.rack_no)), 60);
ok('a group starts at its own rack_from rather than at 1');

// ── several groups together ───────────────────────────────────────────────
const groups = [
  { rack_from: 1, rack_to: 50, shelves: 7, bins: 3, bin_capacity: 30 },
  { rack_from: 51, rack_to: 60, shelves: 5, bins: 13, bin_capacity: 80 },
];
const all = buildTargetBins(groups);
assert.equal(all.length, 50 * 7 * 3 + 10 * 5 * 13);
assert.equal(all.find((b) => b.rack_no === 1).capacity, 30);
assert.equal(all.find((b) => b.rack_no === 55).capacity, 80);
assert.equal(all.filter((b) => b.rack_no === 55).length, 5 * 13);
ok('each group keeps its own shape, side by side with the others');

// Groups of different shapes do not interfere: no rack number appears twice.
const seen = new Set();
for (const b of all) {
  const key = `${b.rack_no}:${b.shelf_no}:${b.bin_no}`;
  assert.ok(!seen.has(key), `duplicate bin ${key}`);
  seen.add(key);
}
ok('appended groups never collide on a bin coordinate');

// ── reading existing racks back into groups (the migration) ───────────────
// Shape of one row as the migration's GROUP BY produces it.
const rackRow = (fk_org_id, rack_no, shelves, bins, cap, opts = {}) => ({
  fk_org_id, rack_no, shelves, bins,
  min_cap: opts.min_cap ?? cap, max_cap: cap,
  bin_count: opts.bin_count ?? shelves * bins,
});

// The case that actually matters: a warehouse set up under the old model as one
// uniform grid. It must come back as exactly one group, not fifty.
const uniform = Array.from({ length: 50 }, (_, i) => rackRow(1, i + 1, 7, 3, 30));
const folded = coalesceRackGroups(uniform);
assert.equal(folded.length, 1, '50 identical racks are one group');
assert.deepEqual(
  { ...folded[0] },
  { fk_org_id: 1, rack_from: 1, rack_to: 50, shelves: 7, bins: 3, bin_capacity: 30, uniform: true }
);
ok('a uniform grid folds into a single group');

// The round trip is the property the migration depends on: describing the racks
// as groups and regenerating bins from those groups must reproduce exactly the
// bins that were there. If this drifts, the migration silently misdescribes a
// real warehouse.
const original = buildTargetBins([
  { rack_from: 1, rack_to: 50, shelves: 7, bins: 3, bin_capacity: 30 },
  { rack_from: 51, rack_to: 60, shelves: 5, bins: 13, bin_capacity: 80 },
  { rack_from: 61, rack_to: 61, shelves: 1, bins: 1, bin_capacity: 5 },
]);
// Rebuild the per-rack summary the migration's SQL would return.
const byRack = new Map();
for (const b of original) {
  const cur = byRack.get(b.rack_no) || { shelves: 0, bins: 0, caps: [], n: 0 };
  cur.shelves = Math.max(cur.shelves, b.shelf_no);
  cur.bins = Math.max(cur.bins, b.bin_no);
  cur.caps.push(b.capacity);
  cur.n += 1;
  byRack.set(b.rack_no, cur);
}
const summarised = [...byRack.entries()].sort((a, z) => a[0] - z[0]).map(([rack_no, r]) => ({
  fk_org_id: 1, rack_no, shelves: r.shelves, bins: r.bins,
  min_cap: Math.min(...r.caps), max_cap: Math.max(...r.caps), bin_count: r.n,
}));

const regrouped = coalesceRackGroups(summarised);
assert.equal(regrouped.length, 3, 'three distinct shapes, three groups');
assert.deepEqual(regrouped.map((g) => [g.rack_from, g.rack_to]), [[1, 50], [51, 60], [61, 61]]);
assert.deepEqual(
  buildTargetBins(regrouped).sort(binOrder),
  original.slice().sort(binOrder),
  'regenerating from the derived groups reproduces the original bins exactly'
);
ok('groups derived from existing racks round-trip back to the same bins');

// Two orgs' racks never fold together, even where their numbering is adjacent.
const twoOrgs = coalesceRackGroups([
  rackRow(1, 1, 2, 2, 50), rackRow(1, 2, 2, 2, 50),
  rackRow(2, 3, 2, 2, 50), rackRow(2, 4, 2, 2, 50),
]);
assert.equal(twoOrgs.length, 2);
assert.deepEqual(twoOrgs.map((g) => g.fk_org_id), [1, 2]);
ok('racks belonging to different organizations never fold into one group');

// A gap in the numbering breaks the run — racks 1,2 then 5,6 are two groups
// even though the shape is identical. This is what keeps the migration correct
// once the remove-racks flow can leave holes.
const gapped = coalesceRackGroups([
  rackRow(1, 1, 2, 2, 50), rackRow(1, 2, 2, 2, 50),
  rackRow(1, 5, 2, 2, 50), rackRow(1, 6, 2, 2, 50),
]);
assert.deepEqual(gapped.map((g) => [g.rack_from, g.rack_to]), [[1, 2], [5, 6]]);
ok('a gap in the rack numbering splits the group');

// A ragged rack cannot be folded: mixed capacities within one rack, or fewer
// bins than the shape implies, each isolate it into its own group.
const mixedCaps = coalesceRackGroups([
  rackRow(1, 1, 2, 2, 50),
  rackRow(1, 2, 2, 2, 50, { min_cap: 10 }),   // capacities differ inside rack 2
  rackRow(1, 3, 2, 2, 50),
]);
assert.deepEqual(mixedCaps.map((g) => [g.rack_from, g.rack_to]), [[1, 1], [2, 2], [3, 3]]);
assert.equal(mixedCaps[1].uniform, false);
ok('a rack with mixed bin capacities is isolated rather than folded');

const holey = coalesceRackGroups([
  rackRow(1, 1, 2, 2, 50),
  rackRow(1, 2, 2, 2, 50, { bin_count: 3 }),  // 3 bins where 2x2 implies 4
  rackRow(1, 3, 2, 2, 50),
]);
assert.deepEqual(holey.map((g) => [g.rack_from, g.rack_to]), [[1, 1], [2, 2], [3, 3]]);
ok('a rack missing some of its bins is isolated rather than folded');

assert.deepEqual(coalesceRackGroups([]), [], 'no racks means no groups');
ok('an empty warehouse produces an empty group list');

// ── diff / blockers ───────────────────────────────────────────────────────
// Adding racks does not use these, but the remove-racks flow will, and they are
// the safety net that says which bins may be deleted.
const existing = [
  { id: 1, rack_no: 1, shelf_no: 1, bin_no: 1, capacity: 100, used: 0 },
  { id: 2, rack_no: 1, shelf_no: 1, bin_no: 2, capacity: 100, used: 40 },
  { id: 3, rack_no: 1, shelf_no: 2, bin_no: 1, capacity: 100, used: 0 },
];
const target = [
  { rack_no: 1, shelf_no: 1, bin_no: 1, capacity: 100 },  // keep, unchanged
  { rack_no: 1, shelf_no: 1, bin_no: 2, capacity: 150 },  // keep, capacity up
  { rack_no: 1, shelf_no: 1, bin_no: 3, capacity: 150 },  // add
];

const d = diffLayout(existing, target);
assert.equal(d.add.length, 1);
assert.deepEqual(d.add[0], { rack_no: 1, shelf_no: 1, bin_no: 3, capacity: 150 });
assert.equal(d.keep.length, 2);
assert.equal(d.remove.length, 1);
assert.equal(d.remove[0].id, 3, 'R01-S02-B01 is no longer in the target');
ok('diff classifies bins into add / keep / remove');

assert.deepEqual(
  findBlockers(diffLayout([{ id: 1, rack_no: 1, shelf_no: 1, bin_no: 1, capacity: 100, used: 0 }], [])),
  [],
  'an empty removed bin is not a blocker'
);
ok('removing an empty bin is allowed');

const occupied = findBlockers(diffLayout(
  [{ id: 9, rack_no: 4, shelf_no: 7, bin_no: 2, capacity: 100, used: 60 }],
  []
));
assert.equal(occupied.length, 1);
assert.equal(occupied[0].kind, 'occupied');
assert.equal(occupied[0].id, 9);
ok('removing a bin that holds stock is a blocker');

const shrunk = findBlockers(diffLayout(
  [{ id: 7, rack_no: 2, shelf_no: 1, bin_no: 1, capacity: 100, used: 80 }],
  [{ rack_no: 2, shelf_no: 1, bin_no: 1, capacity: 50 }]
));
assert.equal(shrunk.length, 1);
assert.equal(shrunk[0].kind, 'capacity');
assert.equal(shrunk[0].used, 80);
assert.equal(shrunk[0].capacity, 50);
ok('lowering capacity below current stock is a blocker');

console.log('  -- pure-function checks passed --');

// ── DB-backed checks ──────────────────────────────────────────────────────
const { pool, pingDb, applyAuthSchema } = await import('./src/db.js');
const { getLayout, addRacks, getOrgWidths } = await import('./src/services/layoutService.js');

if (await pingDb()) {
  console.log('  ! MySQL unreachable - skipping the DB-backed layout checks');
} else {
  await applyAuthSchema();
  const VASTRA_ID = 'checklayout-test-org';
  await pool.query('DELETE FROM organization WHERE vastra_org_id = ?', [VASTRA_ID]);
  const [ins] = await pool.query(
    'INSERT INTO organization (vastra_org_id, name) VALUES (?, ?)',
    [VASTRA_ID, 'Check Layout Org']
  );
  const ORG = ins.insertId;

  // A brand-new org is unconfigured and has no racks.
  const fresh = await getLayout(ORG);
  assert.equal(fresh.configured, false);
  assert.equal(fresh.counts.bins, 0);
  assert.deepEqual(fresh.groups, []);
  ok('a new organization starts unconfigured with no groups');

  // First batch: 3 racks x 2 shelves x 2 bins = 12 bins, numbered from 1.
  const first = await addRacks(ORG, {
    racks: 3, shelves: 2, bins: 2, bin_capacity: 100, userId: 'test',
  });
  assert.equal(first.added, 12);
  assert.equal(first.rack_from, 1);
  assert.equal(first.rack_to, 3);
  const after = await getLayout(ORG);
  assert.equal(after.configured, true);
  assert.equal(after.counts.bins, 12);
  assert.equal(after.groups.length, 1);
  assert.equal(after.groups[0].seq, 1);
  assert.equal(after.groups[0].rack_count, 3);
  assert.equal(after.groups[0].capacity, 12 * 100);
  ok('the first batch generates racks × shelves × bins, numbered from 1');

  assert.deepEqual(await getOrgWidths(ORG), { rack: 2, shelf: 2, bin: 2 });
  ok('widths derive from the generated bins');

  // Second batch, different shape: appended after rack 3, leaving batch 1 alone.
  const second = await addRacks(ORG, {
    racks: 2, shelves: 1, bins: 5, bin_capacity: 40, userId: 'test',
  });
  assert.equal(second.rack_from, 4, 'appended after the highest existing rack');
  assert.equal(second.rack_to, 5);
  assert.equal(second.added, 2 * 1 * 5);

  const two = await getLayout(ORG);
  assert.equal(two.groups.length, 2);
  assert.equal(two.groups[1].seq, 2);
  assert.equal(two.counts.bins, 12 + 10);
  assert.equal(two.counts.racks, 5);
  assert.equal(two.counts.capacity, 12 * 100 + 10 * 40);
  ok('a second batch of a different shape appends without touching the first');

  // The first batch's bins are untouched, shape and capacity both.
  const [firstBatchBins] = await pool.query(
    'SELECT capacity FROM rack_master WHERE fk_org_id = ? AND rack_no <= 3', [ORG]
  );
  assert.equal(firstBatchBins.length, 12);
  assert.ok(firstBatchBins.every((b) => b.capacity === 100));
  ok('adding racks never alters the bins already there');

  // Stock in an existing bin must not stand in the way of adding more racks —
  // this is the case the old preview/apply pair blocked on and this one cannot.
  const [[stockBin]] = await pool.query(
    'SELECT id FROM rack_master WHERE fk_org_id = ? AND rack_no = 1 AND shelf_no = 1 AND bin_no = 1',
    [ORG]
  );
  await pool.query(
    'INSERT INTO item_location (fk_org_id, item, color, size, qty, fk_rack_id) VALUES (?,?,?,?,?,?)',
    [ORG, 'Cotton Twill', 'Navy', 'L', 40, stockBin.id]
  );
  await pool.query('UPDATE rack_master SET used = 40, status = ? WHERE id = ?', ['Occupied', stockBin.id]);

  const third = await addRacks(ORG, {
    racks: 1, shelves: 1, bins: 1, bin_capacity: 10, userId: 'test',
  });
  assert.equal(third.rack_from, 6);
  const [[stillThere]] = await pool.query(
    'SELECT used FROM rack_master WHERE id = ?', [stockBin.id]
  );
  assert.equal(Number(stillThere.used), 40, 'stock survives an unrelated add');
  ok('adding racks works while other racks hold stock, and leaves that stock alone');

  // Growth re-pads labels: 6 racks -> 150 means R01 becomes R001, without any
  // bin being recreated.
  await addRacks(ORG, { racks: 144, shelves: 1, bins: 1, bin_capacity: 10, userId: 'test' });
  assert.deepEqual(await getOrgWidths(ORG), { rack: 3, shelf: 2, bin: 2 });
  const [[survivor]] = await pool.query('SELECT id FROM rack_master WHERE id = ?', [stockBin.id]);
  assert.ok(survivor, 'the original bin still exists after growth');
  ok('growing the rack count re-pads labels without recreating bins');

  // Bad input is refused before anything is written.
  const before = (await getLayout(ORG)).counts.bins;
  for (const bad of [
    { racks: 0, shelves: 1, bins: 1, bin_capacity: 1 },
    { racks: 1, shelves: -2, bins: 1, bin_capacity: 1 },
    { racks: 1, shelves: 1, bins: 1, bin_capacity: 0 },
    { racks: 1.5, shelves: 1, bins: 1, bin_capacity: 1 },
  ]) {
    await assert.rejects(addRacks(ORG, { ...bad, userId: 'test' }), /positive integer/i);
  }
  assert.equal((await getLayout(ORG)).counts.bins, before, 'a refused add writes nothing');
  ok('non-positive or fractional numbers are refused and write nothing');

  await assert.rejects(
    addRacks(ORG, { racks: 10000, shelves: 100, bins: 100, bin_capacity: 1, userId: 'test' }),
    /limit/i
  );
  assert.equal((await getLayout(ORG)).counts.bins, before, 'an oversized add writes nothing');
  ok('an absurdly large batch is refused rather than inserting millions of rows');

  await pool.query('DELETE FROM organization WHERE id = ?', [ORG]);
}

await pool.end();
console.log('\nlayout checks passed\n');
