import PDFDocument from 'pdfkit';

// Printable picklist. Deliberately laid out to match the on-screen table —
// same columns, same order — so a picker holding the sheet and someone at the
// portal are reading the same thing.
//
// Streams into the response; pdfkit needs no headless browser.

const COLS = [
  { key: 'item', label: 'Item / Design', width: 150 },
  { key: 'color', label: 'Color', width: 75 },
  { key: 'size', label: 'Size', width: 55 },
  { key: 'qty', label: 'Qty', width: 40, align: 'right' },
  { key: 'racks', label: 'Rack', width: 175 },
];

const MARGIN = 40;
const ROW_PAD = 6;

// pdfkit's standard-font encoding silently DROPS characters it can't map, so
// em dashes vanish mid-sentence. Plain ASCII punctuation throughout.
const fmtDate = (d) => (d ? new Date(d).toLocaleString('en-GB', { dateStyle: 'medium', timeStyle: 'short' }) : '-');

function header(doc, picklist, orgName) {
  doc.font('Helvetica-Bold').fontSize(18).fillColor('#111').text('Picklist', MARGIN, MARGIN);

  doc.font('Helvetica').fontSize(9).fillColor('#666');
  const right = doc.page.width - MARGIN;
  doc.text(orgName || '', MARGIN, MARGIN + 4, { width: right - MARGIN, align: 'right' });

  let y = MARGIN + 26;
  const meta = [
    picklist.dc_no ? ['Challan No', picklist.dc_no] : null,
    picklist.party ? ['Party', picklist.party] : null,
    ['Generated', fmtDate(picklist.created_at)],
    ['Total qty', String(picklist.total_qty)],
    picklist.short_qty > 0 ? ['Short', String(picklist.short_qty)] : null,
    ['Racks updated', picklist.rack_updated ? `Yes - ${picklist.picked_qty} picked on ${fmtDate(picklist.picked_at)}` : 'No'],
  ].filter(Boolean);

  for (const [label, value] of meta) {
    doc.font('Helvetica').fontSize(9).fillColor('#888').text(`${label}`, MARGIN, y, { width: 80 });
    doc.font('Helvetica-Bold').fontSize(9).fillColor('#222').text(value, MARGIN + 85, y, { width: 380 });
    y += 14;
  }
  return y + 10;
}

function tableHead(doc, y) {
  let x = MARGIN;
  doc.rect(MARGIN, y - 4, doc.page.width - MARGIN * 2, 20).fill('#f2f4f7');
  doc.font('Helvetica-Bold').fontSize(9).fillColor('#444');
  for (const c of COLS) {
    doc.text(c.label, x + ROW_PAD, y + 2, { width: c.width - ROW_PAD * 2, align: c.align || 'left' });
    x += c.width;
  }
  return y + 20;
}

export function renderPicklistPdf(picklist, orgName, stream) {
  const doc = new PDFDocument({ size: 'A4', margin: MARGIN, info: {
    Title: picklist.dc_no ? `Picklist ${picklist.dc_no}` : `Picklist #${picklist.id}`,
  } });
  doc.pipe(stream);

  let y = header(doc, picklist, orgName);
  y = tableHead(doc, y);

  doc.font('Helvetica').fontSize(9);
  for (const line of picklist.lines) {
    // Row height follows the tallest cell — a line sitting in several racks
    // wraps rather than overprinting the next row.
    const racks = line.racks || 'Not in any rack';
    const rackHeight = doc.heightOfString(racks, { width: COLS[4].width - ROW_PAD * 2 });
    const itemHeight = doc.heightOfString(line.item, { width: COLS[0].width - ROW_PAD * 2 });
    const rowHeight = Math.max(rackHeight, itemHeight, 12) + ROW_PAD * 2;

    if (y + rowHeight > doc.page.height - MARGIN - 20) {
      doc.addPage();
      y = tableHead(doc, MARGIN);
      doc.font('Helvetica').fontSize(9);
    }

    const cells = {
      item: line.item,
      color: line.color || '-',
      size: line.size || '-',
      qty: String(line.qty),
      racks,
    };

    let x = MARGIN;
    for (const c of COLS) {
      doc.fillColor(c.key === 'racks' && !line.racks ? '#b42318' : '#222');
      doc.text(cells[c.key], x + ROW_PAD, y + ROW_PAD, {
        width: c.width - ROW_PAD * 2, align: c.align || 'left',
      });
      x += c.width;
    }

    // Shortage is the one thing a picker must not miss on paper.
    if (line.shortage > 0) {
      doc.font('Helvetica-Bold').fontSize(8).fillColor('#b42318')
        .text(`short by ${line.shortage}`, MARGIN + COLS[0].width + COLS[1].width + COLS[2].width + COLS[3].width - 60,
          y + ROW_PAD + 11, { width: 60, align: 'right' });
      doc.font('Helvetica').fontSize(9);
    }

    y += rowHeight;
    doc.moveTo(MARGIN, y).lineTo(doc.page.width - MARGIN, y).strokeColor('#e4e7ec').lineWidth(0.5).stroke();
  }

  doc.font('Helvetica-Bold').fontSize(9).fillColor('#111')
    .text(`Total  ${picklist.total_qty}`, MARGIN, y + ROW_PAD, { width: 465, align: 'right' });

  doc.font('Helvetica').fontSize(8).fillColor('#98a2b3')
    .text('Generated by RMS - Rack Management System', MARGIN, doc.page.height - MARGIN - 10);

  doc.end();
}
